// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/lks-go/yandex-praktikum-diploma/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// Calculator is an autogenerated mock type for the Calculator type
type Calculator struct {
	mock.Mock
}

// Accrual provides a mock function with given fields: ctx, orderNumber
func (_m *Calculator) Accrual(ctx context.Context, orderNumber string) (*service.Order, error) {
	ret := _m.Called(ctx, orderNumber)

	if len(ret) == 0 {
		panic("no return value specified for Accrual")
	}

	var r0 *service.Order
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (*service.Order, error)); ok {
		return rf(ctx, orderNumber)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) *service.Order); ok {
		r0 = rf(ctx, orderNumber)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*service.Order)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, orderNumber)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCalculator creates a new instance of Calculator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCalculator(t interface {
	mock.TestingT
	Cleanup(func())
}) *Calculator {
	mock := &Calculator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
