// Code generated by mockery v2.43.0. DO NOT EDIT.

package mocks

import (
	context "context"

	service "github.com/lks-go/yandex-praktikum-diploma/internal/service"
	mock "github.com/stretchr/testify/mock"
)

// OrderProcessPublisher is an autogenerated mock type for the OrderProcessPublisher type
type OrderProcessPublisher struct {
	mock.Mock
}

// Publish provides a mock function with given fields: ctx, msg
func (_m *OrderProcessPublisher) Publish(ctx context.Context, msg service.OrderEvent) {
	_m.Called(ctx, msg)
}

// NewOrderProcessPublisher creates a new instance of OrderProcessPublisher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewOrderProcessPublisher(t interface {
	mock.TestingT
	Cleanup(func())
}) *OrderProcessPublisher {
	mock := &OrderProcessPublisher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
